#!/bin/sh

# This script sets a bunch of Openfire properties so that we can skip the
# install wizard.   When Openfire is initialized the first time, call this
# script to set all the properties.  This also handles the case where the
# end user changes the LDAP base DN.  When that happens, this script is
# called with the "ldap" parameter.

source $(dirname $0)/openfire-functions.sh

sleep 2
# Bail if LDAP has not been initialized
#--------------------------------------

LDAP_CONFIG="/var/clearos/openldap/config.php"

if [ ! -e "$LDAP_CONFIG" ]; then
    logger -p local6.notice -t installer "app-openfire-core - skipping initialization, no LDAP yet"
    exit 0
fi

BASE_DN=`grep "^base_dn =" $LDAP_CONFIG | awk '{ print $3 }'`
BIND_DN=`grep "^bind_dn =" $LDAP_CONFIG | awk '{ print $3 }'`
BIND_PW=`grep "^bind_pw =" $LDAP_CONFIG | awk '{ print $3 }'`
BASE_DOMAIN=`echo $BASE_DN | sed 's/,/./' | sed 's/dc=//g'`

# Bail if network has not been initialized
#-----------------------------------------

source /etc/clearos/network.conf

if ( [ -z "$DEFAULT_DOMAIN" ] || [ -z "$INTERNET_HOSTNAME" ] ); then
    logger -p local6.notice -t installer "app-openfire-core - skipping initialization, no hostname settings"
fi

# It is best to disable Openfire while setting properties
#--------------------------------------------------------

IS_RUNNING=`pidof -x openfire-start`
if [ -n "$IS_RUNNING" ]; then
    systemctl stop openfire
fi

# Set properties
#----------------

setProperty 'ldap.baseDN' "$BASE_DN"
# setProperty 'ldap.adminDN' '7256faef0d0d8b600ee852d35561bd3fbe1d3794430210038f1c4411d9b1d146d8d897cad24323ce78d269902f29bb190117d3ca66da31232797d405845251e21db2f76a6def09efa70ec630677df5a4a62f09b4b77fc98b'
#setProperty 'ldap.adminPassword' '636454402ea5f66ad23a1d89b8970937953ef69e529a2204da539fcd6480e5ebdd99290a411a08bbc7e9194e779b99d5'
setProperty 'ldap.searchFilter' "(memberof=cn=openfire_plugin,ou=Groups,ou=Accounts,$BASE_DN)"

# FIXME move this to Webconfig GUI
setProperty 'admin.authorizedJIDs' "test@$BASE_DOMAIN"

# Only do these on install
if [ "$1" == "install" ]; then
    setProperty 'xmpp.domain' "$DEFAULT_DOMAIN"
    setProperty 'xmpp.fqdn' "$INTERNET_HOSTNAME"
fi

# Restart Openfire
#-----------------

if [ -n "$IS_RUNNING" ]; then
    systemctl start openfire
fi
